services:
  kohya-ss-gui:
    container_name: kohya-ss-gui
    image: localhost/kohya_ss:hina
    user: 1000:0
    logging:
      driver: k8s-file
    build:
      context: .
      args:
        - UID=1000
      # cache_from:
      #   - ghcr.io/bmaltais/kohya-ss-gui
      # cache_to:
      #   - type=inline
    ports:
      - 7862:7860
    environment:
      SAFETENSORS_FAST_GPU: 1
      TENSORBOARD_PORT: ${TENSORBOARD_PORT:-6006}
      TZ: Asia/Taipei
      TRANSFORMERS_CACHE: /home/1000/.cache/huggingface
      TRITON_CACHE_DIR: /home/1000/.triton
    tmpfs:
      - /tmp
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./dataset:/dataset
      - ./dataset/images:/app/data
      - ./dataset/logs:/app/logs
      # - ./dataset/outputs:/app/outputs
      - ./dataset/regularization:/app/regularization
      - ./.cache/config:/app/config
      - ./.cache/user:/home/1000/.cache
      - ./.cache/triton:/home/1000/.triton
      - ./.cache/nv:/home/1000/.nv
      - ./.cache/keras:/home/1000/.keras
      - ./.cache/config:/home/1000/.config # For backward compatibility
      - ./setup.log:/app/setup.log
      - /mnt/ssd/AI/docker-stable-diffusion-webui/data/models/Stable-diffusion:/home/1000/.cache/models
      - /mnt/ssd/AI/docker-stable-diffusion-webui/data/models/text_encoder:/home/1000/.cache/models/text_encoder
      - /mnt/data/AI/SD/data/models/VAE:/home/1000/.cache/models/VAE
      - /mnt/data/AI/AITraining/outputs:/app/outputs
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              device_ids: ["all"]

  tensorboard:
    container_name: tensorboard
    image: tensorflow/tensorflow:latest-gpu
    ports:
      # !Please change the port in .env file
      - ${TENSORBOARD_PORT:-6006}:6006
    environment:
      TZ: Asia/Taipei
    volumes:
      - ./dataset/logs:/app/logs
    command: /bin/bash -c "pip install tensorboard && tensorboard --logdir=/app/logs --bind_all"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              device_ids: ["all"]
